- name: "Tools"
  icon: "toolbox"
  links:
    - name: "GitHub"
      url: "https://www.github.com"
    - name: "GitLab"
      url: "https://www.gitlab.com"
    - name: "BitBucket"
      url: "https://www.bitbucket.com"
    - name: "Docker"
      url: "https://www.docker.com"

- name: "Media"
  icon: "cassette-tape"
  desc: "description"
  links:
    - name: "Plex"
      url: "https://www.plex.tv"
    - name: "NetFlix"
      url: "https://www.netflix.com"
    - name: "Hulu"
      url: "https://www.hulu.com"
    - name: "Disney+"
      url: "https://www.disneyplus.com"

- name: "Productivity"
  desc: "description"
  icon: "qr-code"
  links:
    - name: "Trello"
      url: "https://www.trello.com"
    - name: "Notion"
      url: "https://www.notion.so"
    - name: "Google Drive"
      url: "https://www.drive.google.com"
    - name: "Dropbox"
      url: "https://www.dropbox.com"

- name: "Social"
  desc: "description"
  links:
    - name: "Reddit"
      url: "https://www.reddit.com"
    - name: "Twitter"
      url: "https://www.twitter.com"
    - name: "LinkedIn"
      url: "https://www.linkedin.com"
    - name: "StackOverflow"
      url: "https://www.stackoverflow.com"
